### PR TITLE
Clean up `EnumSet`

### PR DESCRIPTION
**Pull request by tbu-**
Make `EnumSet` portable by using a fixed-size unsigned intger, `u32` as
storage. The previous choice of `uint` created portability hazards as the error
checking is done at runtime.

Mark the `from_u32` method of the trait `CLike` as unsafe, as it is supposed to
be implemented without error checking.

Code using `EnumSet` needs to be updated to use `u32`s.

### CODE REVIEW

**Comment by Gankro** [comment]
@tbu- ping

**Comment by tbu-** [comment]
@Gankro pong – Is there an open question?

**Comment by Gankro** [comment]
I believe this is good to go, pending the one fix discussed.

**Comment by tbu-** [comment]
@Gankro I rebased it and added `InvariantType`. It has a compilation error, but in a different module, I'm not sure if it's my `rustc` that is too old.

**Comment by Gankro** [comment]
Travis seems to be happy, and it uses nightly?

**Comment by cgaebel** [comment]
needs rebase, but r+

**Comment by tbu-** [comment]
@cgaebel Rebased.

**Comment by cgaebel** [comment]
\o/ Thanks!

**Pull request merged**
