### PR TITLE
Feature gate each mod to allow selective compiling

### PR DESCRIPTION
**Pull request by csherratt**
This is in response to en early comment by @Gankro 
>Although we're getting kinda bloaty, I think I need to do what @huonw suggested with adding a feature-per-collection.

This also makes the `collect-rs` possible to use right now since right now it will ICE the compiler.

### CODE REVIEW

**Comment by Gankro** [comment]
:heart: 

I'm not familiar with feature staging, but this *looks* right to me.

r? @reem

**Comment by huonw** [comment]
Maybe `all` could be a default feature?

**Comment by reem** [comment]
I was about to suggest the same thing. All should be default, so users only
have to be familiar with this system if they want to opt in to it.

I'll give a real review later, on my phone now.

**Comment by reem** [comment]
My main concern from seeing other packages deal with stuff like this is ensuring that every combination of feature flags actually works. Testing with only `default` is not enough, since it's very easy to forget to put the correct `#[cfg]` flags on every single use of a feature-gated item.

Ideally we'd have travis build with every single flag independently - that would catch the majority of forgotten configs.

**Comment by csherratt** [comment]
@reem I have added tests for each feature.

**Comment by Gankro** [comment]
eff it

**Pull request merged**
