### PR TITLE
add `IntoIterator` impls

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by Gankro** [comment]
Travis build fails, but it looks like it might be nightly update stuff.

**Comment by apasel422** [comment]
Yeah, it's an issue with changes to `Send`. I'm not familiar enough with `ParVec` to update it.

**Comment by Gankro** [comment]
Currently working on updating to alpha2

**Comment by Gankro** [comment]
I'm 90% sure compare::Borrow just doesn't work with new coherence

**Comment by apasel422** [comment]
Can you elaborate? (Code example, error message?) I'm not seeing any problems with it on `rustc 1.0.0-nightly (dfc5c0f1e 2015-02-18) (built 2015-02-19)`.

**Comment by Gankro** [comment]
I'm running a build of master from last night, where new coherence rules have kicked in and `Q: BorrowFrom<K> -> K: Borrow<Q>`.

But I think I might have figured it out.

**Comment by Gankro** [comment]
Got it working :sparkling_heart:

**Comment by apasel422** [comment]
Rebased.

**Comment by Gankro** [comment]
wooooo

**Pull request merged**
