### PR TITLE
Update to Rust master

### PR DESCRIPTION
**Pull request by apasel422**
This should pass after https://github.com/reem/rust-traverse/pull/17 is merged.

### CODE REVIEW

**Comment by apasel422** [comment]
Actually, it needs to wait for a new version of `traverse` to be pushed to crates.io.

**Comment by Gankro** [comment]
Published traverse, restarting travis build.

**Comment by Gankro** [comment]
Passed, great!

**Comment by Gankro** [comment]
0.0.11 released.

Seriously, thanks a ton! :sparkling_heart:

**Pull request merged**
