### PR TITLE
Implement iterators for LruCache

### PR DESCRIPTION
**Pull request by csouth3**
This is extremely straightforward now that LruCache just became a wrapper around LinkedHashMap.

I tried to also knock out indexing while I was doing this, but there are different problems preventing both `Index` and `IndexMut` from being implemented right now so I'll save them for another PR, they both require some thought.

### CODE REVIEW

**Comment by csouth3** [comment]
Actually, waiiiit.  This doesn't seem entirely correct as I'm reflecting on it, because these accesses should surely be changing the LRU stuff...

**Comment by Gankro** [comment]
It's not clearly useful to be able to iterate or index into an LRUCache. It's... a cache. You try to use it to avoid recomputing values, but need to be entirely prepared that nothing you ask for is actually in there.

Right?

**Comment by csouth3** [comment]
You've a point there, I just saw the FIXME and went for it without really thinking about how it doesn't exactly make the most sense. :p I'm gonna go ahead and close because I agree that this isn't clearly useful enough.  D'oh.

**Comment by Gankro** [comment]
Yeah I think we can remove the FIXMEs. I tossed those in there while doing bulk passes of all the collections and didn't want to think about it too hard.

**Pull request closed without merging**
