### PR TITLE
replace `compare` module with external `compare` crate

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by Gankro** [comment]
Didn't you want to provide some kind of deprecation?

**Comment by apasel422** [comment]
I can re-export the crate and add a deprecation notice, if you want.

**Comment by apasel422** [comment]
Apparently stability attributes no longer apply to third-party crates, so we can still re-export the crate, but can't apply a deprecation notice to it, except in doc form. I doubt many people are using this module directly, so I'm in favor of just removing it outright.

**Comment by Gankro** [comment]
Works for me

**Pull request merged**
