### PR TITLE
add integrity checks to `TreeMap`

### PR DESCRIPTION
**Pull request by apasel422**
And remove some cruft.

cc #85

### CODE REVIEW

**Comment by apasel422** [comment]
I will be moving `check_{left,right}` into `is_valid` and adding some tests. Don't merge yet.

**Comment by Gankro** [comment]
Under what contexts will ndebug be set for downstream dependencies? This is pretty epic bloat if you don't have that set.

**Comment by apasel422** [comment]
Per [crates.io](http://doc.crates.io/manifest.html#the-[profile.*]-sections):
> Cargo supports custom configuration of how rustc is invoked through profiles at the top level. Any manifest may declare a profile, but only the top level project's profiles are actually read. All dependencies' profiles will be overridden. This is done so the top-level project has control over how its dependencies are compiled.

https://github.com/rust-lang/rfcs/pull/563 is relevant, but doesn't appear to affect the _usage_ of `debug_assert`.

**Comment by Gankro** [comment]
Could we perhaps roll our own cfg for integrity checks, so that these only run in true testing?

**Comment by apasel422** [comment]
Could certainly use an explicit #[cfg(test)], but if this isn't the use
case for debug_assert, what is?

**Comment by Gankro** [comment]
The problem is that this is *insanely* expensive. I think debug_asserts are generally for cheap-but-not-free things. Like optional bounds checks.

**Comment by apasel422** [comment]
In that case, I can add a macro like `test_assert` that requires `cfg(test)` and use it instead of `debug_assert`. If that sounds good to you, I can update `IntervalHeap` to do the same thing.

**Comment by apasel422** [comment]
If we migrate to `cfg(test)`-only, then we might not want this after all. The tests can just perform the integrity checks directly, as they were doing previously.

**Pull request closed without merging**
